emit:
  - "@typespec/openapi3"
  - "@azure-tools/typespec-java"
options:
  "@typespec/openapi3":
    output-file: "{project-root}/../.openapi3.azure/openapi3-azure-openai.yaml"
  "@azure-tools/typespec-csharp":
    namespace: "Azure.AI.OpenAI"
    emitter-output-dir: "{project-root}/../.dotnet.azure/src"
    generate-convenience-methods: false
    unreferenced-types-handling: keepAll
    model-namespace: false
    generate-test-project: false
    single-top-level-client: true
    new-project: false
    flavor: "unbranded"
  "@azure-tools/typespec-java":
    output-folder: "{project-root}/../.java.azure"
    package-dir: "azure-ai-openai"
    namespace: "com.azure.ai.openai"
    partial-update: true
    enable-sync-stack: true
    generate-tests: false
    custom-types-subpackage: "implementation.models"
    flavor: "azure"
