# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/specification
    - sdk/specification/ci.yml
    - sdk/specification/Azure.AI.OpenAI

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/specification
    - sdk/specification/ci.yml
    - sdk/specification/Azure.AI.OpenAI

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: specification
    ArtifactName: packages
    Artifacts:
    - name: Azure.AI.OpenAI
      safeName: AzureAIOpenAI
